name: Build Test and Publish a Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  prep:
    runs-on: buildjet-4vcpu-ubuntu-2204
    outputs:
      branch: ${{ steps.whichver.outputs.branch }}
    steps:
      - uses: actions/checkout@v3

      - name: Determine package version
        shell: bash
        run: |
          branch=${GITHUB_REF#refs/heads/}
          echo branch="${branch}" >> $GITHUB_OUTPUT
        id: whichver

  build-ubuntu-jammy-aarch64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    needs: prep

    steps:
      - name: Build
        uses: jaldistech/edgedb-pkg/integration/linux/build/ubuntu-jammy@master
        env:
          SRC_REF: "${{ needs.prep.outputs.branch }}"
          PKG_REVISION: "<current-date>"
          PKG_PLATFORM: "ubuntu"
          PKG_PLATFORM_VERSION: "jammy"
          EXTRA_OPTIMIZATIONS: "true"
          BUILD_IS_RELEASE: "true"
          METAPKG_GIT_CACHE: disabled

      - uses: actions/upload-artifact@v3
        with:
          name: builds-ubuntu-jammy-aarch64
          path: artifacts/ubuntu-jammy

  # test-ubuntu-jammy-aarch64:
  #   needs: [build-ubuntu-jammy-aarch64]
  #   runs-on: buildjet-4vcpu-ubuntu-2204-arm
  #
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: builds-ubuntu-jammy-aarch64
  #         path: artifacts/ubuntu-jammy
  #
  #     - name: Test
  #       uses: edgedb/edgedb-pkg/integration/linux/test/ubuntu-jammy@master
  #       env:
  #         PKG_PLATFORM: "ubuntu"
  #         PKG_PLATFORM_VERSION: "jammy"
  #         PKG_PLATFORM_LIBC: ""
  #         # edb test with -j higher than 1 seems to result in workflow
  #         # jobs getting killed arbitrarily by Github.
  #         PKG_TEST_JOBS: 0

  collect:
    needs: [build-ubuntu-jammy-aarch64]
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - run: echo 'All build+tests passed, ready to publish now!'

  publish-ubuntu-jammy-aarch64:
    needs: [collect]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: builds-ubuntu-jammy-aarch64
          path: artifacts/ubuntu-jammy

      - name: Publish
        uses: edgedb/edgedb-pkg/integration/linux/upload/linux-x86_64@master
        env:
          PACKAGE_SERVER: sftp://uploader@package-upload.jaldis.com:8025/
          PKG_PLATFORM: "ubuntu"
          PKG_PLATFORM_VERSION: "jammy"
          PKG_PLATFORM_LIBC: ""
          PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"
